#!/usr/bin/env ruby
require 'pathname'
require 'open3'
require 'singleton'
require 'open-uri'
require 'rexml/document'

SPARKLE_MIN_VERSION = Gem::Version.new('1.13.1')
ATS_MIN_SDK_MAJOR = 15.freeze
CHECK_PAST_VERSIONS_IN_FEED = !ENV['CHECK_PAST_VERSIONS_IN_FEED'].to_i.zero? || false

class System
  include Singleton
  
  def build_version
    out = `sw_vers`
    version = out.match(/BuildVersion:\s+([A-Z0-9]+)/)[1]
    version.split(/[a-z]/i).first.to_i
  end
  
  def ats_available?
    build_version >= ATS_MIN_SDK_MAJOR
  end
end

class PlistBuddy
  BIN = '/usr/libexec/PlistBuddy'.freeze
  
  class KeyNotFound < StandardError
  end
  
  def self.exec(path, command)
    out, status = Open3.capture2e("#{BIN} -c \"#{command}\" \"#{path}\"")
    out = out.chomp
    unless status.success?
      if out =~ /Does Not Exist$/
        raise KeyNotFound, out
      else
        raise out
      end
    end
    out
  end

  def self.read(path, keypath)
    keypath = keypath.join(':') if keypath.is_a?(Array)
    exec(path, "Print :#{keypath}")
  end
end

class App
  def self.system_apps
    Pathname.glob('/Applications/**.app').map { |path| App.new(path) }
  end
  
  def self.user_apps
    Pathname.glob('/Users/*/Applications/**.app').map { |path| App.new(path) }
  end
  
  def self.preference_panes
    %w(
      /Users/*/Library/PreferencePanes
      /System/Library/PreferencePanes
      /Library/PreferencePanes
    ).flat_map do |dir|
      Pathname.glob("#{dir}/*.prefPane").map { |path| App.new(path) }
    end
  end
  
  attr_reader :path
  
  def initialize(path)
    @path = path
  end
  
  def info_plist_path
    path + 'Contents/Info.plist'
  end
  
  def bundle_identifier
    @bundle_identifier ||= PlistBuddy.read(info_plist_path, :CFBundleIdentifier)
  end
  
  def version
    @version ||= PlistBuddy.read(info_plist_path, :CFBundleShortVersionString) rescue ''
  end
  
  def user_defaults_path
    Pathname('~/Library/Preferences') + "#{bundle_identifier}.plist"
  end
  
  def synced_user_defaults_path
    Pathname('~/Library/SyncedPreferences') + "#{bundle_identifier}.plist"
  end
  
  def sparke_framework_path
    path + 'Contents/Frameworks/Sparkle.framework'
  end
  
  def executable_name
    @executable_name ||= PlistBuddy.read(info_plist_path, :CFBundleExecutable)
  end
  
  def executable_path
    @executable_path ||= path + 'Contents/MacOS' + executable_name
  end
  
  def uses_sparkle?
    File.exist?(sparke_framework_path)
  end
  
  def sparkle_version
    return @sparkle_version if defined?(@sparkle_version)
    @sparkle_version ||= PlistBuddy.read(path + 'Contents/Frameworks/Sparkle.framework/Versions/Current/Resources/Info.plist', :CFBundleShortVersionString) rescue nil
  end
  
  def is_sparkle_outdated?
    return true if sparkle_version.nil?
    @is_sparkle_outdated ||= begin
      parseable_version, _ = sparkle_version.split(' ')
      parseable_version.gsub!('##VERSION##', version) if parseable_version =~ /##VERSION##/
      Gem::Version.new(parseable_version) < SPARKLE_MIN_VERSION
    end
  end
  
  def allows_arbitrary_loads?
    @allows_arbitrary_loads ||= PlistBuddy.read(info_plist_path, [:NSAppTransportSecurity, :NSAllowsArbitraryLoads]) rescue false
  end
  
  def transport_security_exception_domains
    @transport_security_exception_domains ||= PlistBuddy.read(info_plist_path, [:NSAppTransportSecurity, :NSExceptionDomains]) rescue ''
  end
  
  def has_insecure_exceptions?
    @has_insecure_exceptions ||= !!(@transport_security_exception_domains =~ /NS(ThirdParty)?ExceptionAllowsInsecureHTTPLoads = false/)
  end
  
  def sparkle_feed_url
    return @sparkle_feed_url if defined?(@sparkle_feed_url)
    @sparkle_feed_url = read_feed_url_from_path(synced_user_defaults_path)
    @sparkle_feed_url ||= read_feed_url_from_path(user_defaults_path)
    @sparkle_feed_url ||= read_feed_url_from_path(info_plist_path)
  end
  
  def read_feed_url_from_path(path)
    return nil unless path.exist?
    value = PlistBuddy.read(path, :SUFeedURL)
    return nil if value.empty? || value == 'NULL'
    value
  rescue PlistBuddy::KeyNotFound
    nil
  end
  
  def exposes_feed_url?
    !sparkle_feed_url.nil?
  end
  
  def uses_insecure_feed_url?
    @uses_insecure_feed_url ||= begin
      if exposes_feed_url?
        !!(sparkle_feed_url =~ /^http\:/)
      elsif !insecure_feed_urls_in_executable.empty?
        true
      end
    end
  end
  
  def uses_insecure_elements?
    uses_insecure_feed_url? || !insecure_release_notes_links_in_feed.empty?
  end
  
  def insecure_release_notes_links_in_feed
    @insecure_release_notes_links_in_feed ||= check_release_notes
  end
  
  def check_release_notes
    @error_while_checking_release_notes = nil
    return [] unless exposes_feed_url?
    puts "ℹ Check AppCast at #{sparkle_feed_url}."
    body = open(sparkle_feed_url)
    doc = REXML::Document.new(body)
    REXML::XPath.each(doc.root, "//channel/item/sparkle:releaseNotesLink").select do |node|
      next false unless node.text != nil && node.text =~ /^http\:/
      next true if CHECK_PAST_VERSIONS_IN_FEED
      enclosure_tag = node.parent.elements["enclosure"]
      node_version = enclosure_tag.attributes["sparkle:shortVersionString"]
      Gem::Version.new(node_version) > Gem::Version.new(self.version)
    end.map(&:text)
  rescue => error
    puts "✗ Check failed with error: #{error}".red
    @error_while_checking_release_notes = error
    []
  end
  
  def error_while_checking_release_notes
    check_release_notes unless defined?(@error_while_checking_release_notes)
    @error_while_checking_release_notes
  end
  
  def sdk_build
    @sdk_build ||= PlistBuddy.read(info_plist_path, :DTSDKBuild) rescue nil
  end
  
  def ats_enabled?
    return @ats_enabled if defined?(@ats_enabled)
    @ats_enabled ||= sdk_build.nil? ? false : sdk_build.split(/[a-z]/i).first.to_i >= ATS_MIN_SDK_MAJOR
  end
  
  def allows_insecure_access?
    !System.instance.ats_available? || !ats_enabled? || allows_arbitrary_loads? || has_insecure_exceptions?
  end
  
  def urls_in_executable
    @urls_in_executable ||= `strings "#{executable_path}" | grep -C0 --color=never -E "^https?:"`.chomp.split("\n")
  end
  
  def insecure_urls_in_executable
    @insecure_urls_in_executable ||= urls_in_executable.select { |url| url =~ /^http:/ }
  end
  
  def insecure_feed_urls_in_executable
    return @insecure_feed_url_in_executable unless @insecure_feed_url_in_executable.nil?
    @insecure_feed_url_in_executable = begin
      insecure_urls_in_executable.select { |url| url =~ /(update|changelog|appcast)/ }
    end
  end

  def risk_classification
    @risk_classification ||= if uses_insecure_elements?
      if allows_insecure_access?
        :danger
      else
        :broken_updater
      end
    elsif !exposes_feed_url? && allows_insecure_access?
      :unknown
    else
      :unaffected
    end
  end
end

class String
  def green
    "\033[0;32m#{self}\e[0m"
  end

  def yellow
    "\033[0;33m#{self}\e[0m"
  end

  def red
    "\033[0;31m#{self}\e[0m"
  end
end

if ARGV.count == 1
  app_path = Pathname(ARGV[0])
  unless app_path.exist?
    puts "The given path doesn't exist.".red
    exit 1
  end
  app = App.new(app_path)
  unless app.info_plist_path.exist?
    puts "Can't find a valid app at the given path".red
    exit 1
  end
  apps = [App.new(app_path)]
else
  apps = App.system_apps + App.user_apps + App.preference_panes
end

puts "Analyze …"

sparkle_updated_apps = apps.select(&:uses_sparkle?)
outdated_apps = sparkle_updated_apps.select(&:is_sparkle_outdated?)
grouped_apps = outdated_apps.group_by(&:risk_classification)
potential_vulnerable_apps = outdated_apps - (grouped_apps[:unaffected] || [])

puts "Report:"
puts "Examined #{apps.count} apps and preference panes of which #{sparkle_updated_apps.count} are updated via Sparkle.".green
puts "#{outdated_apps.count} of these use outdated versions of Sparkle, which don't include the checked security patch.".yellow
if !System.instance.ats_available?
  puts "ℹ ATS is not available on your OS version.".yellow
end
if potential_vulnerable_apps.count > 0
  puts "The following #{potential_vulnerable_apps.count} of these are potentially vulnerable:".red
  puts
else
  puts 'No potentially vulnerable apps were detected. 🎉'.green
end

grouped_apps = potential_vulnerable_apps.group_by(&:risk_classification)
[:danger, :unknown, :broken_updater].each do |risk_classification|
  next unless grouped_apps[risk_classification]
  grouped_apps[risk_classification].each do |app|
    puts "* #{app.path.basename}"
    puts "  Version: #{app.version}"
    puts "  Sparkle Version: '#{app.sparkle_version}'"
    puts "  Feed URL: #{app.sparkle_feed_url}" if app.exposes_feed_url?

    if !System.instance.ats_available?
      # This is shown once in the beginning and not per app.
    elsif !app.ats_enabled?
      puts "  ✗ ATS is not active".red
    else
      puts "  ✓ ATS is active".green
      if app.allows_arbitrary_loads?
        puts "  ✗ Allows arbitrary loads".red
      else 
        puts "  ✓ Doesn't allow arbitrary loads".green
      end
      if app.has_insecure_exceptions?
        puts "  ✗ Has insecure ATS exceptions:".red
        puts "      " + app.transport_security_exception_domains.split("\n").join("\n      ")
      else 
        puts "  ✓ Doesn't have insecure ATS exceptions".green
      end
    end
    
    case app.uses_insecure_feed_url?
      when true  then
        puts "  ✗ Uses an insecure Feed URL".red
        unless app.exposes_feed_url?
          puts "    as indicated by the URLs found in the executable:".red
          puts "      " + app.insecure_feed_urls_in_executable.join("\n      ")
          puts "    ℹ This heuristic can yield false-positives.".yellow
        end
      when false then
        puts "  ✓ Uses a secure Feed URL".green
        if app.error_while_checking_release_notes != nil
          puts "  ℹ Couldn't validate whether the are insecure elements in the AppFeed".yellow
        elsif !app.insecure_release_notes_links_in_feed.empty?
          puts "  ✗ Has links to insecure release notes in AppFeed:".red
          puts "      " + app.insecure_release_notes_links_in_feed.join("\n      ")
          puts "    ℹ This must be fixed on the server-side. Please note the developer to fix this issue.".red
        end
      when nil   then
        puts "  ℹ Doesn't expose the Feed URL".yellow
        unless app.insecure_urls_in_executable.empty?
          puts "  ℹ Has insecure URLs in its executable:".yellow
          puts "      " + app.insecure_urls_in_executable.join("\n      ")
          puts "    If any of these URLs provides the appcast, then this app is vulnerable."
        else 
          puts "  ✓ Doesn't have any insecure URLs in its executable".green
        end
    end

    classification = case app.risk_classification
      when :danger         then 'IMMINENT DANGER'.red
      when :broken_updater then 'BROKEN UPDATER'.yellow
      when :unknown        then 'UNKNOWN'.yellow
      when :unaffected     then 'UNAFFECTED'.green
    end
    puts "  Risk classification: #{classification}"
    
    puts
  end
end
